/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class HomeForm extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel mainPanel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeForm.class.getName());

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        khoiTaoPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnQuanLy = new javax.swing.JMenu();
        mniQLSach = new javax.swing.JMenuItem();
        mniQLDocGia = new javax.swing.JMenuItem();
        mniQLTacGia = new javax.swing.JMenuItem();
        mnHeThong = new javax.swing.JMenu();
        mniPhieuMuon = new javax.swing.JMenuItem();
        mniImPort = new javax.swing.JMenuItem();
        mniExPort = new javax.swing.JMenuItem();
        mnTroGiup = new javax.swing.JMenu();
        mnTaiKhoan = new javax.swing.JMenu();
        mniThongTinTaiKhoan = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        mnQuanLy.setText("Quản lý");

        mniQLSach.setText("Quản lý sách");
        mnQuanLy.add(mniQLSach);

        mniQLDocGia.setText("Quản lý độc giả");
        mnQuanLy.add(mniQLDocGia);

        mniQLTacGia.setText("Quản lý tác giả");
        mnQuanLy.add(mniQLTacGia);

        jMenuBar1.add(mnQuanLy);

        mnHeThong.setText("Hệ thống");

        mniPhieuMuon.setText("Phiếu mượn");
        mnHeThong.add(mniPhieuMuon);

        mniImPort.setText("Import");
        mnHeThong.add(mniImPort);

        mniExPort.setText("Export");
        mnHeThong.add(mniExPort);

        jMenuBar1.add(mnHeThong);

        mnTroGiup.setText("Trợ giúp");
        jMenuBar1.add(mnTroGiup);

        mnTaiKhoan.setText("Tài khoản");

        mniThongTinTaiKhoan.setText("Thông tin tài khoản");
        mnTaiKhoan.add(mniThongTinTaiKhoan);

        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mniDangXuat);

        jMenuBar1.add(mnTaiKhoan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        // Đóng HomeForm hiện tại
        this.dispose();
        // Mở LoginForm
        LoginForm login = new LoginForm();
        login.setLocationRelativeTo(null); // căn giữa màn hình
        login.setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenu mnTaiKhoan;
    private javax.swing.JMenu mnTroGiup;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniExPort;
    private javax.swing.JMenuItem mniImPort;
    private javax.swing.JMenuItem mniPhieuMuon;
    private javax.swing.JMenuItem mniQLDocGia;
    private javax.swing.JMenuItem mniQLSach;
    private javax.swing.JMenuItem mniQLTacGia;
    private javax.swing.JMenuItem mniThongTinTaiKhoan;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables

    private void khoiTaoPanel() {
        // Gắn CardLayout vào pnlContent (panel bạn kéo thả trong design)
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        mainPanel.add(new QuanLyDocGiaPanel(), "QL_DOCGIA");
        mainPanel.add(new QuanLySachPanel(), "QL_SACH");
        mainPanel.add(new QuanLyTacGiaPanel(), "QL_TACGIA");
        mainPanel.add(new QuanLyPhieuMuonPanel(), "QL_PHIEUMUON");

        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlContent.add(mainPanel, java.awt.BorderLayout.CENTER);
        pnlContent.revalidate();
        pnlContent.repaint();

        // Xử lý sự kiện menu
        mniQLDocGia.addActionListener(e -> cardLayout.show(mainPanel, "QL_DOCGIA"));
        mniQLSach.addActionListener(e -> cardLayout.show(mainPanel, "QL_SACH"));
        mniQLTacGia.addActionListener(e -> cardLayout.show(mainPanel, "QL_TACGIA"));
        mniPhieuMuon.addActionListener(e -> cardLayout.show(mainPanel, "QL_PHIEUMUON"));

    }
}
