/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ExportDAO;
import dao.ImportDAO;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class NhapXuatPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhapXuatPanel
     */
    public NhapXuatPanel() {
        initComponents();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnNhap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboTenBangNhap = new javax.swing.JComboBox<>();
        txtDuongDanNhapFile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnChonTepNhap = new javax.swing.JButton();
        btnNhapFile = new javax.swing.JButton();
        pnXuat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboTenBangXuat = new javax.swing.JComboBox<>();
        txtDuongDanXuatFile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnChonTepXuat = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel-100.png"))); // NOI18N
        jLabel1.setText("NHẬP XUẤT ");

        pnNhap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nhập dữ liệu từ excel");

        cboTenBangNhap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Đường dẫn file");

        btnChonTepNhap.setText("Chọn tệp ");
        btnChonTepNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTepNhapActionPerformed(evt);
            }
        });

        btnNhapFile.setText("Nhập");
        btnNhapFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNhapLayout = new javax.swing.GroupLayout(pnNhap);
        pnNhap.setLayout(pnNhapLayout);
        pnNhapLayout.setHorizontalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhapLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTenBangNhap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnNhapLayout.createSequentialGroup()
                        .addComponent(txtDuongDanNhapFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonTepNhap)))
                .addContainerGap())
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnNhapFile, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        pnNhapLayout.setVerticalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTenBangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonTepNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuongDanNhapFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhapFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pnXuat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Xuất dữ liệu ra excel");

        cboTenBangXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Đường dẫn file");

        btnChonTepXuat.setText("Chọn đường dẫn");
        btnChonTepXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTepXuatActionPerformed(evt);
            }
        });

        btnXuatFile.setText("Xuất");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnXuatLayout = new javax.swing.GroupLayout(pnXuat);
        pnXuat.setLayout(pnXuatLayout);
        pnXuatLayout.setHorizontalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTenBangXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(txtDuongDanXuatFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonTepXuat))
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnXuatLayout.setVerticalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTenBangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuongDanXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonTepXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonTepXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTepXuatActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn thư mục để xuất file Excel");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Chỉ chọn folder
        chooser.setAcceptAllFileFilterUsed(false); // Không hiển thị file

        int result = chooser.showOpenDialog(this); // Mở hộp thoại chọn thư mục
        if (result == JFileChooser.APPROVE_OPTION) {
            String folderPath = chooser.getSelectedFile().getAbsolutePath();
            txtDuongDanXuatFile.setText(folderPath); // Gán vào textfield hiển thị đường dẫn
        }
    }//GEN-LAST:event_btnChonTepXuatActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        String folderPath = txtDuongDanXuatFile.getText().trim();
        if (folderPath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thư mục để xuất file!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tenBang = cboTenBangXuat.getSelectedItem().toString();
        boolean success = false;

        try {
            if (tenBang.equalsIgnoreCase("Tất cả")) {
                // Xuất tất cả bảng
                success = ExportDAO.exportDocGia(folderPath)
                        & ExportDAO.exportTacGia(folderPath)
                        & ExportDAO.exportSach(folderPath)
                        & ExportDAO.exportPhieuMuon(folderPath)
                        & ExportDAO.exportChiTietMuon(folderPath);
            } else {
                // Xuất 1 bảng cụ thể
                switch (tenBang) {
                    case "Độc Giả":
                        success = ExportDAO.exportDocGia(folderPath);
                        break;
                    case "Tác Giả":
                        success = ExportDAO.exportTacGia(folderPath);
                        break;
                    case "Sách":
                        success = ExportDAO.exportSach(folderPath);
                        break;
                    case "Phiếu Mượn":
                        success = ExportDAO.exportPhieuMuon(folderPath);
                        break;
                    case "Chi Tiết Mượn":
                        success = ExportDAO.exportChiTietMuon(folderPath);
                        break;
                }
            }

            if (success) {
                JOptionPane.showMessageDialog(this, "Xuất Excel thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Xuất Excel thất bại!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnChonTepNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTepNhapActionPerformed
        // TODO add your handling code here:
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Chọn file Excel để import");
    
    // Chỉ cho phép chọn file
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    
    // Lọc chỉ nhận file Excel
    chooser.setAcceptAllFileFilterUsed(false);
    chooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files", "xlsx", "xls"));

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        String filePath = chooser.getSelectedFile().getAbsolutePath();
        String fileName = chooser.getSelectedFile().getName();
        String baseName = fileName.contains(".") ? fileName.substring(0, fileName.lastIndexOf('.')) : fileName;

        List<String> danhSachBang = Arrays.asList("DocGia", "TacGia", "Sach", "PhieuMuon", "ChiTietMuon");
        if (!danhSachBang.contains(baseName)) {
            JOptionPane.showMessageDialog(this, "Tên file phải trùng với tên bảng SQL (DocGia, TacGia, Sach, PhieuMuon, ChiTietMuon)!", 
                                          "Lỗi tên file", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Nếu đúng → gán vào textfield hiển thị đường dẫn
        txtDuongDanNhapFile.setText(filePath);
        // Optional: chọn combo theo tên bảng tự động
        cboTenBangNhap.setSelectedItem(baseName);
    }
    }//GEN-LAST:event_btnChonTepNhapActionPerformed

    private void btnNhapFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileActionPerformed
        // TODO add your handling code here:
        String filePath = txtDuongDanNhapFile.getText().trim();
    if (filePath.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa chọn file Excel!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String tenBang = cboTenBangNhap.getSelectedItem().toString();
    boolean success = false;

    try {
        switch (tenBang) {
            case "Độc Giả":
                success = ImportDAO.importDocGia(filePath);
                break;
            case "Tác Giả":
                success = ImportDAO.importTacGia(filePath);
                break;
            case "Sách":
                success = ImportDAO.importSach(filePath);
                break;
            case "Phiếu Mượn":
                success = ImportDAO.importPhieuMuon(filePath);
                break;
            case "Chi Tiết Mượn":
                success = ImportDAO.importChiTietMuon(filePath);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Tên bảng không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
        }

        if (success) {
            JOptionPane.showMessageDialog(this, "Import thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Import thất bại! Kiểm tra dữ liệu hoặc ràng buộc khóa.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Lỗi khi import: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnNhapFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonTepNhap;
    private javax.swing.JButton btnChonTepXuat;
    private javax.swing.JButton btnNhapFile;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cboTenBangNhap;
    private javax.swing.JComboBox<String> cboTenBangXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnNhap;
    private javax.swing.JPanel pnXuat;
    private javax.swing.JTextField txtDuongDanNhapFile;
    private javax.swing.JTextField txtDuongDanXuatFile;
    // End of variables declaration//GEN-END:variables

    private void loadComboBox() {
        cboTenBangNhap.removeAllItems();
        cboTenBangXuat.removeAllItems();

        String[] dsBang = {"Độc Giả", "Tác Giả", "Sách", "Phiếu Mượn", "Chi Tiết Mượn"};

        for (String bang : dsBang) {
            cboTenBangNhap.addItem(bang);
        }

        cboTenBangXuat.addItem("Tất cả");
        for (String bang : dsBang) {
            cboTenBangXuat.addItem(bang);
        }
    }
}
